=== codehaus/mapbuilder/trunk/mapbuilder/mapbuilder/lib/schemas/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema targetNamespace="http://mapbuilder.sourceforge.net/mapbuilder" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mb="http://mapbuilder.sourceforge.net/mapbuilder" elementFormDefault="qualified" version="0.2.0">
	<xs:annotation>
		<xs:appinfo>$Id$</xs:appinfo>
		<xs:documentation xml:lang="en">
			<xs:description>Application schema for Mapbuilder runtime configuration</xs:description>
			<xs:copyright>License: GPL as per: http://www.gnu.org/copyleft/gpl.html</xs:copyright>
		</xs:documentation>
	</xs:annotation>
	<!-- imports -->
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<!-- global model extension types -->
	<xs:complexType name="ContextType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractModelType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ContextCollectionType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractModelType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Gml2Type">
		<xs:complexContent>
			<xs:extension base="mb:AbstractModelType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ModelBaseType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractModelType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DescribeFeatureTypeType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractModelType"/>
		</xs:complexContent>
	</xs:complexType>
	<!-- global widget extension types -->
	<xs:complexType name="MapPaneType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType">
				<xs:sequence>
					<xs:element name="htmlTagId" type="xs:string"/>
					<xs:element name="mapContainerId" type="xs:string"/>
					<xs:element name="fixedWidth" type="xs:integer" minOccurs="0"/>
					<xs:element name="fixedHeight" type="xs:integer" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="LegendType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CursorTrackType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType">
				<xs:sequence>
					<xs:element name="mouseHandler" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="WidgetBaseType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="AoiFormType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="WmsCapabilitiesImportType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CollectionListType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="FeatureListType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="LocationsType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="GmlRendererType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType">
				<xs:sequence>
					<xs:element name="htmlTagId" type="xs:string"/>
					<xs:element name="mapContainerId" type="xs:string"/>
					<xs:element name="pointDiameter" type="xs:integer"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Gml2RenderType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType">
				<xs:sequence>
					<xs:element name="htmlTagId" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ButtonBarType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="WebServiceFormType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractWidgetType">
				<xs:sequence>
					<xs:element name="webServiceUrl" type="xs:anyURI"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- global tools extension types -->
	<xs:complexType name="AoiMouseHandlerType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="AoiBoxType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DragPanHandlerType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType">
				<xs:sequence>
					<xs:element name="enabled" type="xs:boolean"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MouseClickHandlerType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ZoomToAoiType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ZoomInType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ZoomOutType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DragPanType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SetAoiType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ResetType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="GetFeatureInfoType">
		<xs:complexContent>
			<xs:extension base="mb:AbstractToolType">
				<xs:sequence>
					<xs:element name="targetFeatureCollection" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!--	document structure -->
	<xs:element name="MapbuilderConfig" type="mb:MapbuilderConfigType"/>
	<xs:complexType name="MapbuilderConfigType">
		<xs:sequence>
			<xs:element name="skinDir" type="mb:urlPathType" minOccurs="0"/>
			<xs:element name="proxyUrl" type="mb:urlPathType" minOccurs="0"/>
			<xs:element name="models" type="mb:modelsType" minOccurs="0"/>
			<xs:element name="widgets" type="mb:widgetsType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="version" type="xs:string" use="required" fixed="0.2.0"/>
		<xs:attribute name="id" type="mb:idType" use="required"/>
	</xs:complexType>
	<xs:complexType name="modelsType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Context" type="mb:ContextType"/>
			<xs:element name="ContextCollection" type="mb:ContextCollectionType"/>
			<xs:element name="Gml2" type="mb:Gml2Type"/>
			<xs:element name="ModelBase" type="mb:ModelBaseType"/>
			<xs:element name="DescribeFeatureType" type="mb:DescribeFeatureTypeType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="widgetsType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="MapPane" type="mb:MapPaneType"/>
			<xs:element name="CursorTrack" type="mb:CursorTrackType"/>
			<xs:element name="Legend" type="mb:LegendType"/>
			<xs:element name="WidgetBase" type="mb:WidgetBaseType"/>
			<xs:element name="AoiForm" type="mb:AoiFormType"/>
			<xs:element name="WmsCapabilitiesImport" type="mb:WmsCapabilitiesImportType"/>
			<xs:element name="CollectionList" type="mb:CollectionListType"/>
			<xs:element name="FeatureList" type="mb:FeatureListType"/>
			<xs:element name="Locations" type="mb:LocationsType"/>
			<xs:element name="GmlRenderer" type="mb:GmlRendererType"/>
			<xs:element name="Gml2Render" type="mb:Gml2RenderType"/>
			<xs:element name="ButtonBar" type="mb:ButtonBarType"/>
			<xs:element name="WebServiceForm" type="mb:WebServiceFormType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="toolsType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="AoiMouseHandler" type="mb:AoiMouseHandlerType"/>
			<xs:element name="AoiBox" type="mb:AoiBoxType"/>
			<xs:element name="DragPanHandler" type="mb:DragPanHandlerType"/>
			<xs:element name="MouseClickHandler" type="mb:MouseClickHandlerType"/>
			<xs:element name="ZoomToAoi" type="mb:ZoomToAoiType"/>
			<xs:element name="ZoomIn" type="mb:ZoomInType"/>
			<xs:element name="ZoomOut" type="mb:ZoomOutType"/>
			<xs:element name="DragPan" type="mb:DragPanType"/>
			<xs:element name="SetAoi" type="mb:SetAoiType"/>
			<xs:element name="Reset" type="mb:ResetType"/>
			<xs:element name="GetFeatureInfo" type="mb:GetFeatureInfoType"/>
		</xs:choice>
	</xs:complexType>
	<!-- 	global base types -->
	<xs:complexType name="AbstractModelType" abstract="true">
		<xs:sequence>
			<xs:element name="defaultModelUrl" type="mb:urlPathType" minOccurs="0"/>
			<xs:element name="widgets" type="mb:widgetsType"/>
		</xs:sequence>
		<xs:attribute name="id" type="mb:idType" use="required"/>
	</xs:complexType>
	<xs:complexType name="AbstractWidgetType" abstract="true">
		<xs:sequence>
			<xs:element name="targetModel" type="xs:string" minOccurs="0"/>
			<xs:element name="lineColor" type="xs:string" minOccurs="0"/>
			<xs:element name="lineWidth" type="xs:integer" minOccurs="0"/>			
			<xs:element name="stylesheet" type="xs:string" minOccurs="0"/>
			<xs:element name="tools" type="mb:toolsType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="mb:idType" use="required"/>
	</xs:complexType>
	<xs:complexType name="AbstractToolType" abstract="true">
		<xs:sequence>
			<xs:element name="targetModel" type="xs:string" minOccurs="0"/>
			<xs:element name="lineColor" type="xs:string" minOccurs="0"/>
			<xs:element name="lineWidth" type="xs:integer" minOccurs="0"/>
			<xs:element name="crossSize" type="xs:integer" minOccurs="0"/>
			<xs:element name="class" type="xs:string" minOccurs="0"/>
			<xs:element name="selected" type="xs:boolean" minOccurs="0"/>
			<xs:element name="mouseHandler" type="xs:string" minOccurs="0"/>
			<xs:element name="dependsOn" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="enabledSrc" type="mb:urlPathType" minOccurs="0"/>
			<xs:element name="disabledSrc" type="mb:urlPathType" minOccurs="0"/>
			<xs:element name="tooltip" type="mb:tooltipType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="mb:idType" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="idType">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>
	<xs:simpleType name="urlPathType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:complexType name="tooltipType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="xml:lang"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>	
</xs:schema>

=== codehaus/mapbuilder/sandbox/ol-integration/mapbuilder/demo/basic/config.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<MapbuilderConfig version="0.2.1" id="simpleTemplate" xmlns="http://mapbuilder.sourceforge.net/mapbuilder" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mapbuilder.sourceforge.net/mapbuilder ../../lib/schemas/config.xsd">
	<models>
		<Context id="mainMap">
			<defaultModelUrl>../data/context/demisWorldMap.xml</defaultModelUrl>
			<widgets>
				<MapPaneOL id="mainMapWidget">
					<htmlTagId>mainMapPane</htmlTagId>
					<mapContainerId>mainMapContainer</mapContainerId>
				</MapPaneOL>
        <!--Loading2 id="loading2">
					<mapContainerId>mainMapContainer</mapContainerId>
        </Loading2-->
			</widgets>
			<tools>
			</tools>
		</Context>
	</models>
	<widgets>
		<ZoomIn id="zoomIn">
			<buttonBar>mainButtonBar</buttonBar>
			<targetModel>mainMap</targetModel>
			<class>RadioButton</class>
			<selected>true</selected>
			<enabledSrc>/images/ZoomInEnable.png</enabledSrc>
			<disabledSrc>/images/ZoomInDisable.png</disabledSrc>
		</ZoomIn>
		<ZoomOut id="zoomOut">
			<buttonBar>mainButtonBar</buttonBar>
			<targetModel>mainMap</targetModel>
			<class>RadioButton</class>
			<enabledSrc>/images/ZoomOutEnable.png</enabledSrc>
			<disabledSrc>/images/ZoomOutDisable.png</disabledSrc>
		</ZoomOut>
		<DragPan id="dragPan">
			<buttonBar>mainButtonBar</buttonBar>
			<targetModel>mainMap</targetModel>
			<class>RadioButton</class>
			<enabledSrc>/images/PanEnable.png</enabledSrc>
			<disabledSrc>/images/PanDisable.png</disabledSrc>
		</DragPan>
		<Reset id="reset">
			<buttonBar>mainButtonBar</buttonBar>
			<targetModel>mainMap</targetModel>
			<class>Button</class>
			<disabledSrc>/images/ResetExtentDisable.png</disabledSrc>
		</Reset>
	</widgets>
	<skinDir>../../lib/skin/default</skinDir>
	<widgetTextUrl>widgetText.xml</widgetTextUrl>
	<!-- relative to the skin dir -->
</MapbuilderConfig>

=== codehaus/mapbuilder/trunk/mapbuilder/mapbuilder/demo/config/WFSConfig.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<MapbuilderConfig version="0.2.1" 
    id="WFSDemoConfig" 
    xmlns="http://mapbuilder.sourceforge.net/mapbuilder" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://mapbuilder.sourceforge.net/mapbuilder ../../lib/schemas/config.xsd">
  <!--
    Description: This configuration file determines what components from the
                 Mapbuilder library are to be included in a Main Mapbuilder web
                 page.
    Licence:     GPL as per: http://www.gnu.org/copyleft/gpl.html 

    $Id$
  -->

  <models>

    <Context id="mainMap">
      <defaultModelUrl>context/atlasWorld.xml</defaultModelUrl>
      
      <widgets>
        <MapPane id="mainMapWidget">
          <htmlTagId>mainMapPane</htmlTagId>
          <loadHidden>false</loadHidden>
          <tools>
            <AoiMouseHandler/>
            <AoiBox>
              <lineColor>#FF0000</lineColor>
              <lineWidth>2</lineWidth>
              <crossSize>1</crossSize>
            </AoiBox>
            <DragPanHandler>
              <enabled>false</enabled>
            </DragPanHandler>
          </tools>
          <mapContainerId>mainMapContainer</mapContainerId>
        </MapPane>
        <CursorTrack id="cursorTrack">
          <mouseHandler>mainMap.mainMapWidget</mouseHandler>
        </CursorTrack>
            
        <Legend id="legend"/>
        
        <Widget id="mapTitle">
          <stylesheet>/mapbuilder/lib/widget/MapTitle.xsl</stylesheet>
        </Widget>

      </widgets>
        
    </Context>
      
    <Context id="locator">
      <defaultModelUrl>context/locatorMap.xml</defaultModelUrl>
      <widgets>
        <MapPane id="locatorWidget">
          <htmlTagId>locatorMap</htmlTagId>
          <targetModel>mainMap</targetModel>
          <tools>
            <AoiBox>
              <lineColor>red</lineColor>
              <lineWidth>1</lineWidth>
              <crossSize>15</crossSize>
            </AoiBox>
            <AoiMouseHandler/>
            <ZoomToAoi>
            </ZoomToAoi>
          </tools>
          <mapContainerId>locatorContainer</mapContainerId>
          <fixedWidth>180</fixedWidth>
        </MapPane>
      </widgets>
    </Context>
    
  <!-- use this with a WFS capabilities model -->
  
		<WfsCapabilities id="wfsCapTemplate">
      <defaultModelUrl>http://webservices.ionicsoft.com/ionicweb/wfs/BOSTON_ORA?version=1.0.0&amp;service=WFS&amp;request=GetCapabilities</defaultModelUrl>
      <nodeSelectXpath>/wfs:WFS_Capabilities/wfs:FeatureTypeList/wfs:FeatureType</nodeSelectXpath>
      <models>
        <DescribeFeatureType id="featureTypeTemplate" template="true">
          <widgets>
            <Widget id="attributeFilter">
              <stylesheet>/mapbuilder/lib/widget/FilterAttributes.xsl</stylesheet>
              <outputNodeId>filterForm</outputNodeId>
            </Widget>
          </widgets>
        </DescribeFeatureType>
        <GetFeature id="getFeatureTemplate" template="true">
          <widgets>
            <GmlRendererTest id="testGmlRenderer">
              <targetModel>mainMap</targetModel>
              <htmlTagId>mainMapPane</htmlTagId>
              <mapContainerId>mainMapContainer</mapContainerId>
            </GmlRendererTest>
            <SaveModel id="saveModel">
              <htmlTagId>saveModel</htmlTagId>
              <serializeUrl>/mapbuilder/writeXml</serializeUrl>
              <outputNodeId>saveModelOutput</outputNodeId>
            </SaveModel>
          </widgets>
        </GetFeature>
      </models>
			<widgets>
        <Widget id="featureList">
          <stylesheet>/mapbuilder/lib/widget/SelectFeatureType.xsl</stylesheet>
        </Widget>
				<DescribeFeatureTypeRequest>
          <targetModel>featureTypeTemplate</targetModel>
				</DescribeFeatureTypeRequest>
        <GetFeatureRequest id="getFeatureRequest">
          <debug/>
          <targetModel>getFeatureTemplate</targetModel>
          <tools>
          </tools>
        </GetFeatureRequest>
			</widgets>
		</WfsCapabilities>
    
  </models>

  <widgets>
    <ButtonBar id="buttonBar">
      <targetModel>mainMap</targetModel>
      <tools>
        <ZoomIn id="zoomIn">
          <mouseHandler>mainMap.mainMapWidget</mouseHandler>
          <dependsOn>mainMap.mainMapWidget.AoiMouseHandler</dependsOn>
          <dependsOn>mainMap.mainMapWidget.AoiBox</dependsOn>
          <class>RadioButton</class>
          <selected>true</selected>
          <enabledSrc>/images/ZoomInEnable.gif</enabledSrc>
          <disabledSrc>/images/ZoomInDisable.gif</disabledSrc>
          <tooltip xml:lang="en">click and drag to zoom in</tooltip>
          <tooltip xml:lang="fr">cliquer et faire glisser la souris pour agrandir</tooltip>
        </ZoomIn>
        <ZoomOut id="zoomOut">
          <mouseHandler>mainMap.mainMapWidget</mouseHandler>
          <dependsOn>mainMap.mainMapWidget.AoiMouseHandler</dependsOn>
          <dependsOn>mainMap.mainMapWidget.AoiBox</dependsOn>
          <class>RadioButton</class>
          <enabledSrc>/images/ZoomOutEnable.gif</enabledSrc>
          <disabledSrc>/images/ZoomOutDisable.gif</disabledSrc>
          <tooltip xml:lang="en">click to zoom out</tooltip>
          <tooltip xml:lang="fr">cliquer pour réire</tooltip>
        </ZoomOut>
        <DragPan id="dragPan">
          <mouseHandler>mainMap.mainMapWidget</mouseHandler>
          <dependsOn>mainMap.mainMapWidget.DragPanHandler</dependsOn>
          <class>RadioButton</class>
          <enabledSrc>/images/PanEnable.gif</enabledSrc>
          <disabledSrc>/images/PanDisable.gif</disabledSrc>
          <tooltip xml:lang="en">click and drag to pan</tooltip>
          <tooltip xml:lang="fr">cliquer et faire glisser la souris pour voir un autre parti de la carte</tooltip>
        </DragPan>
        <SetAoi id="setAoi">
          <mouseHandler>mainMap.mainMapWidget</mouseHandler>
          <dependsOn>mainMap.mainMapWidget.AoiMouseHandler</dependsOn>
          <dependsOn>mainMap.mainMapWidget.AoiBox</dependsOn>
          <class>RadioButton</class>
          <enabledSrc>/images/SetAoiEnable.gif</enabledSrc>
          <disabledSrc>/images/SetAoiDisable.gif</disabledSrc>
          <tooltip xml:lang="en">click and drag to set the area of interest</tooltip>
          <tooltip xml:lang="fr">cliquer et faire glisser la souris pour positionner une réon d'intét</tooltip>
        </SetAoi>
        <Reset id="reset">
          <class>Button</class>
          <disabledSrc>/images/ResetExtentDisable.gif</disabledSrc>
          <tooltip xml:lang="en">reset the map to full extent</tooltip>
          <tooltip xml:lang="fr">redonner à la carte ses dimensions complès</tooltip>
        </Reset>
        <GetFeatureInfo id="getFeatureInfo">
          <mouseHandler>mainMap.mainMapWidget</mouseHandler>
          <dependsOn>mainMap.mainMapWidget.MouseClickHandler</dependsOn>
          <class>RadioButton</class>
          <enabledSrc>/images/QueryEnable.gif</enabledSrc>
          <disabledSrc>/images/QueryDisable.gif</disabledSrc>
          <tooltip xml:lang="en">click on feature for more info</tooltip>
          <tooltip xml:lang="fr">cliquer pour obtenir plus d'information pour cette couche</tooltip>
          <targetFeatureCollection>gml2</targetFeatureCollection>
        </GetFeatureInfo>
      </tools>
    </ButtonBar>
    <ModelUrlInput id="urlInput">
      <targetModel>wfsCapTemplate</targetModel>
    </ModelUrlInput>
  </widgets>
      
  <!--
    All static images should be relative to this URL.
    This dir is relative the dir of the main html file.
  -->
  <skinDir>/mapbuilder/lib/skin/default</skinDir>
  <proxyUrl>/mapbuilder/proxy?url=</proxyUrl>

</MapbuilderConfig>
